# fly.toml file generated for super-simple-node on 2022-11-10T15:40:51-07:00

app = "node-sqlite-fly-tutorial"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[mounts]
  source = "data"
  destination = "/data"

[experimental]
  enable_consul = true
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "600s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = 5000
    tls_skip_verify = false
    [services.http_checks.headers]
